window.EXIT_LAUNCH_CONFIG=Object.freeze({
  launchMode:'open_core',
  openCore:true,
  founderCapacity:100,
  founderCheckoutOpen:false,
  founderRule:'001-100-never-expanded',
  core:{
    protocol:'framework.html',
    lexicon:'lexicon.html',
    sprint:'30-day-control-sprint.html',
    controlRoom:'control-room.html',
    paymentRequired:false
  },
  crm:{
    provider:'substack',
    fallbackUrl:'https://exitframework.substack.com/subscribe?utm_source=chaosexit&utm_medium=website&utm_campaign=exit_launch'
  },
  social:{instagram:'',youtube:'',tiktok:'',linkedin:''}
});
