(()=> {
const KEY='exit_control_sprint_v1', CAPTURE_KEY='exit_mimir_capture_v1'; const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], clean=v=>String(v||'').trim();
const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}};
const captures=()=>{try{return JSON.parse(localStorage.getItem(CAPTURE_KEY)||'[]')}catch{return[]}};
const latest=s=>Array.isArray(s?.checkins)&&s.checkins.length?[...s.checkins].sort((a,b)=>(+a.day||0)-(+b.day||0)).at(-1):null;
const day=s=>{if(!s?.startedAt)return 1;const a=new Date(s.startedAt+'T00:00:00'),b=new Date();return Math.min(30,Math.max(1,Math.floor((b-a)/86400000)+1))};
const phase=d=>d<=7?'STABILIZE':d<=14?'CONTROL':d<=21?'EXECUTE':'AUTONOMY';
const deriveNow=s=>{if(!s)return{action:'Start or restore the 30-Day Control Sprint.',detail:'Exit needs a state before Mímir can reduce the decision space.'};const d=day(s),today=(s.checkins||[]).find(x=>+x.day===d);if(today?.mission==='planned'&&clean(today.action))return{action:clean(today.action),detail:'Execute one bounded move. Return only to record what happened.'};if(today)return{action:'Stop. Return when reality changes or tomorrow begins.',detail:'Today is recorded. Do not manufacture another obligation.'};return{action:"Set today's operating state and one next action.",detail:'Do not reconstruct missed days. Start from what is true now.'}};
function render(){const s=load(),l=latest(s),d=day(s),fr=s?.controlRoom?.activeFriction,n=deriveNow(s),cap=captures();$('[data-phase]').textContent='PHASE // '+(s?phase(d):'—');$('[data-capacity]').textContent='CAPACITY // '+({green:'USABLE',yellow:'NARROW',red:'STABILIZE'}[l?.state]||'UNSET');$('[data-now]').textContent=n.action;$('[data-now-detail]').textContent=n.detail;const activeFr=fr&&fr.status!=='resolved';$('[data-friction-count]').textContent=activeFr?'1':'0';$('[data-friction-short]').textContent=activeFr?clean(fr.statement).slice(0,28):'Clear';$('[data-archive-count]').textContent=String(cap.length);$('[data-decision-count]').textContent=String((s?.decisions||[]).length||0);$('[data-signal-count]').textContent=String((s?.signals||[]).filter(x=>x.status!=='dismissed').length||0)}
function clock(){$('[data-clock]').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})} clock();setInterval(clock,30000);render();
const drawers={
friction:()=>{const s=load(),fr=s?.controlRoom?.activeFriction;return fr&&fr.status!=='resolved'?[sec('ACTIVE FRICTION',fr.statement,fr.nextAction||'Name the smallest useful next move.')]:[sec('CLEAR','No active friction named.','Nothing needs to be manufactured.')]},
signals:()=>{const s=load(),items=(s?.signals||[]).filter(x=>x.status!=='dismissed').slice(0,5);return items.length?items.map(x=>sec((x.source||'SIGNAL').toUpperCase(),x.text,'Urgency '+(x.urgency??50))):[sec('QUIET','No relevant signals surfaced.','Noise does not earn screen space.')]},
execution:()=>[sec('HP-JARVIS-01','Execution node provisioned.','PREPARE jobs are bounded; EXECUTE remains approval-gated.','https://highpriority.no/command','OPEN DIGITWIN ↗'),sec('BOUNDARY','READ → PREPARE → APPROVE → EXECUTE','Production changes, sending, deletion and money remain gated.')],
decisions:()=>{const s=load(),items=(s?.decisions||[]).slice(0,6);return items.length?items.map(x=>sec('DECISION',x.text||x.statement||'Decision',x.status||'recorded')):[sec('EMPTY','No decisions in this local Exit state.','Use Control Room for deep decision work.')]},
archive:()=>{const items=captures().slice(-6).reverse();return items.length?items.map(x=>sec('CAPTURE',x.text,new Date(x.createdAt).toLocaleString())):[sec('EMPTY','No recent Mímir captures.','Say “fang dette …” to add one.')]},
projects:()=>[sec('EXIT FRAMEWORK','Human operating system / recovery-aware control.','Primary system.','/control-room.html','OPEN CONTROL ROOM ↗'),sec('HIGH PRIORITY','Digitwin / JARVIS / execution node.','HP-JARVIS-01 workspace node.','https://highpriority.no/command','OPEN COMMAND CENTER ↗'),sec('SAKSFREMGANG','B2C case-navigation product.','Workspace-ready on JARVIS.','https://saksfremgang.no','OPEN PRODUCT ↗')]
};
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function sec(k,t,p,url,label){return '<section class="drawer-section"><small>'+esc(k)+'</small><h3>'+esc(t)+'</h3><p>'+esc(p||'')+'</p>'+(url?'<a class="drawer-action" href="'+esc(url)+'">'+esc(label||'OPEN')+'</a>':'')+'</section>'}
const drawer=$('[data-drawer]'),scrim=$('[data-scrim]'),body=$('[data-drawer-body]'),title=$('[data-drawer-title]'),kicker=$('[data-drawer-kicker]');
function openDrawer(name){const fn=drawers[name];if(!fn)return;title.textContent=name.toUpperCase();kicker.textContent='EXIT OS // '+name.toUpperCase();body.innerHTML=fn().join('');drawer.classList.add('open');drawer.setAttribute('aria-hidden','false');scrim.hidden=false}
function closeDrawer(){drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true');scrim.hidden=true}
$$('[data-open]').forEach(b=>b.addEventListener('click',()=>openDrawer(b.dataset.open)));$('[data-close]').addEventListener('click',closeDrawer);scrim.addEventListener('click',closeDrawer);

const palette=$('[data-palette-panel]'),pinput=$('[data-palette-input]');function openPalette(){palette.hidden=false;setTimeout(()=>pinput.focus(),0)}function closePalette(){palette.hidden=true}
$('[data-palette]').addEventListener('click',openPalette);$('[data-palette-close]').addEventListener('click',closePalette);window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openPalette()}if(e.key==='Escape'){closePalette();closeDrawer()}});
$$('[data-cmd]').forEach(b=>b.addEventListener('click',()=>{const c=b.dataset.cmd;closePalette();if(c==='what-now')reply(deriveNow(load()).action);else openDrawer(c.replace('open-',''))}));pinput.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();route(pinput.value);pinput.value='';closePalette()}});

function bestVoice(){if(!('speechSynthesis'in window))return null;const voices=speechSynthesis.getVoices();return voices.find(v=>/^nb|^no/i.test(v.lang)&&/google|natural|online|premium|enhanced|microsoft/i.test(v.name))||voices.find(v=>/^nb|^no/i.test(v.lang))||voices.find(v=>/^sv/i.test(v.lang))||null}
function speak(text){if(!('speechSynthesis'in window)||!text)return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='nb-NO';u.rate=.98;u.pitch=.92;const v=bestVoice();if(v)u.voice=v;speechSynthesis.speak(u)}
const response=$('[data-mimir-response]'),transcript=$('[data-transcript]');function reply(text,voice=true){response.textContent=text;if(voice)speak(text)}
function capture(text){const items=captures();items.push({id:crypto.randomUUID?.()||String(Date.now()),text,createdAt:new Date().toISOString(),status:'captured'});localStorage.setItem(CAPTURE_KEY,JSON.stringify(items.slice(-100)));render()}
function route(raw){const text=clean(raw),q=text.toLowerCase();if(!text)return;transcript.textContent='“'+text+'”';if(/hva.*(gjøre|nå)|neste|mission|oppgave/.test(q))return reply(deriveNow(load()).action);if(/friksjon/.test(q)){openDrawer('friction');return reply('Åpner friksjon.')}if(/signal/.test(q)){openDrawer('signals');return reply('Åpner signaler.')}if(/execution|jarvis|loq/.test(q)){openDrawer('execution');return reply('Åpner execution.')}if(/prosjekt|exit|saksfremgang|high priority/.test(q)){openDrawer('projects');return reply('Åpner prosjekter.')}if(/decision|beslutning/.test(q)){openDrawer('decisions');return reply('Åpner beslutninger.')}if(/arkiv|archive/.test(q)&&!/fang|husk/.test(q)){openDrawer('archive');return reply('Åpner arkivet.')}if(/(fang|husk)/.test(q)){const p=text.replace(/^.*?(fang|husk)(s+dette)?[:;,s-]*/i,'').trim();if(p){capture(p);return reply('Fanget.')}return reply('Si hva jeg skal fange.')}reply('Kommandoen er forstått, men krever Mímir orchestrator før execution.')}
const form=$('[data-command-form]'),input=$('[data-command-input]');form.addEventListener('submit',e=>{e.preventDefault();route(input.value);input.value=''});

const panel=$('[data-voice-panel]'),mic=$('[data-mic]'),state=$('[data-voice-state]'),SR=window.SpeechRecognition||window.webkitSpeechRecognition;let rec=null,finalText='';
if(SR){rec=new SR();rec.lang='nb-NO';rec.interimResults=true;rec.continuous=false;rec.onstart=()=>{speechSynthesis?.cancel();finalText='';panel.classList.add('listening');state.textContent='LISTENING';transcript.textContent='…'};rec.onresult=e=>{let interim='';for(let i=e.resultIndex;i<e.results.length;i++){const h=e.results[i][0].transcript;if(e.results[i].isFinal)finalText+=(finalText?' ':'')+h;else interim+=h}transcript.textContent='“'+(finalText||interim)+'”'};rec.onend=()=>{panel.classList.remove('listening');state.textContent='IDLE';if(finalText)route(finalText)};rec.onerror=e=>{panel.classList.remove('listening');state.textContent='VOICE ERROR';response.textContent=e.error}}
else{state.textContent='TEXT ONLY';mic.disabled=true}
mic.addEventListener('click',()=>{if(rec)try{rec.start()}catch{}});$('[data-voice]').addEventListener('click',()=>mic.click());
window.addEventListener('storage',render);
})();