(()=> {
  const KEY='exit_control_sprint_v1', CAPTURE_KEY='exit_mimir_capture_v1';
  const $=s=>document.querySelector(s), clean=v=>String(v||'').trim();
  const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}};
  const save=s=>{try{localStorage.setItem(KEY,JSON.stringify(s));window.dispatchEvent(new CustomEvent('exit-state:changed',{detail:{source:'mimir-hud'}}));return true}catch{return false}};
  const latest=s=>Array.isArray(s?.checkins)&&s.checkins.length?[...s.checkins].sort((a,b)=>(+a.day||0)-(+b.day||0)).at(-1):null;
  const day=s=>{if(!s?.startedAt)return 1;const a=new Date(s.startedAt+'T00:00:00'),b=new Date();return Math.min(30,Math.max(1,Math.floor((b-a)/86400000)+1))};
  const phase=d=>d<=7?'STABILIZE':d<=14?'CONTROL':d<=21?'EXECUTE':'AUTONOMY';
  const deriveNow=s=>{if(!s)return {action:'Start or restore the 30-Day Control Sprint.',detail:'Exit needs a state before Mímir can reduce the decision space.'};const d=day(s),today=(s.checkins||[]).find(x=>+x.day===d);if(today?.mission==='planned'&&clean(today.action))return {action:clean(today.action),detail:'Execute one bounded move. Return only to record what happened.'};if(today)return {action:'Stop. Return when reality changes or tomorrow begins.',detail:'Today is recorded. Do not manufacture another obligation.'};return {action:"Set today's operating state and one next action.",detail:'Do not reconstruct missed days. Start from what is true now.'}};
  function render(){const s=load(),l=latest(s),d=day(s),fr=s?.controlRoom?.activeFriction,n=deriveNow(s);$('[data-phase]').textContent='PHASE // '+(s?phase(d):'—');$('[data-capacity]').textContent='CAPACITY // '+({green:'USABLE',yellow:'NARROW',red:'STABILIZE'}[l?.state]||'UNSET');$('[data-now]').textContent=n.action;$('[data-now-detail]').textContent=n.detail;$('[data-friction]').textContent=fr&&fr.status!=='resolved'&&clean(fr.statement)?fr.statement:'No active friction named.';$('[data-friction-next]').textContent=fr&&fr.status!=='resolved'?(clean(fr.nextAction)||'Name the smallest useful next move.'):'Nothing needs to be manufactured.';if(l){$('[data-last]').textContent=clean(l.action)||'Latest state recorded.';$('[data-last-detail]').textContent=[l.state?.toUpperCase(),l.mission?.replace('_',' ').toUpperCase(),Number.isFinite(+l.control)?'CONTROL '+l.control+'/10':''].filter(Boolean).join(' · ')}else{$('[data-last]').textContent='No check-in yet.';$('[data-last-detail]').textContent='Leave enough context for the next return.'}}
  function clock(){$('[data-clock]').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}
  function speak(text){if(!('speechSynthesis'in window)||!text)return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='nb-NO';u.rate=.96;window.speechSynthesis.speak(u)}
  function capture(text){let items=[];try{items=JSON.parse(localStorage.getItem(CAPTURE_KEY)||'[]')}catch{}items.push({id:crypto.randomUUID?.()||String(Date.now()),text,createdAt:new Date().toISOString(),status:'captured'});localStorage.setItem(CAPTURE_KEY,JSON.stringify(items.slice(-100)));return items.length}
  function setCapacity(value){const s=load();if(!s)return false;const d=day(s),map={low:'red',lav:'red',red:'red',normal:'yellow',normalen:'yellow',yellow:'yellow',high:'green',høy:'green',green:'green'};const state=map[value];if(!state)return false;const existing=(s.checkins||[]).find(x=>+x.day===d);const entry=existing?{...existing,state}:{date:new Date().toISOString().slice(0,10),day:d,state,action:'Choose one bounded move in Control Room',mission:'planned',control:latest(s)?.control??s.baseline??5,note:'Capacity set from Mímir HUD'};s.checkins=Array.isArray(s.checkins)?s.checkins:[];const i=s.checkins.findIndex(x=>+x.day===d);if(i>=0)s.checkins[i]=entry;else s.checkins.push(entry);return save(s)}
  const response=$('[data-mimir-response]'),transcript=$('[data-transcript]'),note=$('[data-voice-note]');
  function reply(text,voice=true){response.textContent=text;if(voice)speak(text)}
  function route(raw,{voice=true}={}){const text=clean(raw),q=text.toLowerCase();if(!text)return reply('Gi meg én kommando.',voice);
    transcript.textContent='“'+text+'”';
    if(/hva.*(gjøre|nå)|neste|mission|oppgave/.test(q)){const n=deriveNow(load());return reply(n.action,voice)}
    if(/(åpne|vis).*(control|kontroll)/.test(q)){reply('Åpner Control Room.',voice);setTimeout(()=>location.href='control-room.html',450);return}
    if(/kapasitet/.test(q)){const m=q.match(/\b(low|lav|normal|normalen|high|høy|red|yellow|green)\b/);if(m&&setCapacity(m[1])){render();return reply('Kapasitet oppdatert.',voice)}return reply('Si lav, normal eller høy kapasitet.',voice)}
    if(/(fang|husk|capture|arkiv)/.test(q)){const payload=text.replace(/^.*?(fang|husk|capture|arkiv)(\s+dette)?[:;,\s-]*/i,'').trim();if(!payload)return reply('Si hva jeg skal fange.',voice);capture(payload);return reply('Fanget lokalt. Klar for Life Archive-synk.',voice)}
    if(/friksjon/.test(q)){const s=load(),fr=s?.controlRoom?.activeFriction;if(fr&&fr.status!=='resolved')return reply(fr.statement+(fr.nextAction?'. Neste trekk: '+fr.nextAction:''),voice);return reply('Ingen aktiv friksjon er registrert.',voice)}
    if(/(stopp|mute|vær stille|ikke snakk)/.test(q)){window.speechSynthesis?.cancel();response.textContent='Voice muted for this command.';return}
    reply('Jeg har transkribert kommandoen, men den krever Mímir-orchestrator før jeg kan utføre den sikkert.',voice)
  }
  clock();setInterval(clock,30000);render();window.addEventListener('storage',render);window.addEventListener('exit-state:changed',render);
  const form=$('[data-command-form]'),input=$('[data-command-input]');form?.addEventListener('submit',e=>{e.preventDefault();route(input.value);input.value=''});
  const panel=$('[data-voice-panel]'),mic=$('[data-mic]'),state=$('[data-voice-state]'),SR=window.SpeechRecognition||window.webkitSpeechRecognition;let rec=null,active=false,finalText='';
  if(SR){rec=new SR();rec.lang='nb-NO';rec.interimResults=true;rec.continuous=false;rec.onstart=()=>{active=true;finalText='';panel.classList.add('listening');state.textContent='LISTENING';transcript.textContent='…';note.textContent='Lytter. Trykk igjen for å stoppe.'};rec.onresult=e=>{let text='';for(let i=e.resultIndex;i<e.results.length;i++){text+=e.results[i][0].transcript;if(e.results[i].isFinal)finalText+=e.results[i][0].transcript}transcript.textContent='“'+(finalText||text)+'”';state.textContent=e.results[e.results.length-1].isFinal?'UNDERSTOOD':'LISTENING'};rec.onend=()=>{active=false;panel.classList.remove('listening');if(finalText){state.textContent='READY';route(finalText)}else if(state.textContent==='LISTENING'){state.textContent='IDLE'}note.textContent='Voice recognition is provided by your browser. Commands remain approval-gated.'};rec.onerror=e=>{active=false;panel.classList.remove('listening');state.textContent='VOICE ERROR';note.textContent=e.error||'Voice input failed.'}}
  else{mic.disabled=true;state.textContent='UNAVAILABLE';note.textContent='Denne browseren støtter ikke SpeechRecognition. Skriv kommandoen under.'}
  mic?.addEventListener('click',()=>{if(!rec)return;if(active)rec.stop();else{try{rec.start()}catch{}}});$('[data-voice]')?.addEventListener('click',()=>mic?.click());
})();